### ISSUE TITLE
Diffy doesn't output differences when endpoints have responses with non-200 status code

### ISSUE THREAD

**Issue by joaoccgomes** [twitter/diffy#75] opened 2018-07-19 13:01 UTC
I'm trying to use Diffy but I have a strange behaviour when the endpoints have responses with a status code different from 200OK.
Seems that Diffy only checks responses with status code 200OK, if they are 4xx I cannot see any request in the Diffy UI. Is it supposed just to work with success responses?

**Comment by puneetkhanduri** [comment] 2018-07-20 04:11
That is strange. Diffy is designed to work with 4XX responses just as well as it does with 200.
I just tested some endpoints hardcoded to return 400 status codes and am able to see them on the UI. Are you able to verify the networking and see that your primary, secondary and candidate instances are receiving traffic from Diffy?

**Comment by lbatalha** [comment] 2018-07-20 10:40
(coworker here) We have found that if the Primary/Secondary returns a 404 and the Candidate returns a 200, nothing is shown in the Diffy webUI. The opposite appears to work just fine.
Is this working as intended?

**Comment by puneetkhanduri** [comment] 2018-07-20 16:21
No. You should be able to see the differences in both cases. I also just verified this behavior. Can you share the differences.log file generated by diffy.

**Comment by puneetkhanduri** [comment] 2018-07-20 16:51
<img width="482" alt="screen shot 2018-07-20 at 10 08 36 pm" src="https://user-images.githubusercontent.com/1631032/43014831-1dd773ce-8c6b-11e8-9907-c6d0b8efeb4d.png">
you should be seeing something like this for your scenario.

**Comment by lbatalha** [comment] 2018-07-20 17:05
deleted and re-created docker container (diffy/diffy), cleaned up differences.log with `echo "" > differences.log` (it seems to have some test data already there from when the container was built?), verified that it was empty.
Sent a request with an endpoint that only exists in the candidate (`/ping`). Nothing is written to differences.log, nothing in webui. Admin web ui shows successful requests to all 3 backends.
Sent another requests to an endpoint that does not exist in both candidate and current backends and that worked (there was a diff in the webui and in differences.log)

Also (but unrelated since same behaviour happens without it) we have nginx reverse proxying all requests on port 80 back to the candidate node with a mirror option that then mirrors the request to diffy (as this allows us to see a response when submitting the requests). Running the `/ping` request replies with the appropriate response (`pong`).

The image you linked is what shows up when we have a primary return 200 and candidate return 404, just not the opposite for some reason.

**Comment by puneetkhanduri** [comment] 2018-07-20 17:45
Can you ping me at puneet.khanduri@gmail.com. It might be easier to debug this with screen sharing via hangouts.

**Comment by puneetkhanduri** [comment] 2018-07-20 18:38
Turns out this was a case of unsupported content-type where the response header did not contain application/json or text/html. Issue was fixed by having the downstream targets supply the expected content-type header values.

**Comment by lbatalha** [comment] 2018-07-20 18:38
After a very helpful hangouts, it was discovered that the specific endpoint we were using to test this "issue" was returning a content type of `text/plain` on the candidate side. After enabling DEBUG logging for `ai.diffy.lifter.HttpLifter` the stack traced showed a parse error. @puneetkhanduri confirmed that Diffy does not support that content type at this point, only the usual HTML and JSON suspects.

For our use case this is fine because all normal application endpoints use one of those.

**Closed by puneetkhanduri** 2018-07-20 18:38 UTC
